apiVersion: v1
kind: Pod
spec:
  containers:
  - volumeMounts:
    - mountPath: /v3io
      name: v3io-fuse
    - mountPath: /User
      name: v3io-fuse
      subPath: users//admin
    - mountPath: /etc/config/v3io
      name: v3io-config
    - mountPath: /igz/java/crash
      name: igz-java
    - mountPath: /dev/shm
      name: shm
    - mountPath: /var/run/iguazio/dayman
      name: v3iod-comm
    env:
    - name: V3IO_API
      value: v3io-webapi.default-tenant.svc:8081
    - name: V3IO_FRAMESD
      value: framesd:8081
    - name: IGZ_DATA_CONFIG_FILE
      value: /etc/config/v3io/v3io.conf
    - name: CURRENT_NODE_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
  volumes:
  - flexVolume:
      driver: v3io/fuse
      options:
        dirsToCreate: '[{"name": "users//admin", "permissions": 488}]'
      secretRef:
        name: jupyter-v3io-fuse
    name: v3io-fuse
  - configMap:
      defaultMode: 420
      name: spark-worker-v3io-config
    name: v3io-config    
  - emptyDir: {}
    name: igz-java
  - hostPath:
      path: /dev/shm/default-tenant
      type: ""
    name: shm
  - hostPath:
      path: /var/run/iguazio/dayman/default-tenant
      type: ""
    name: v3iod-comm
